# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mechanic', models.BooleanField(default=False)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='statuscode',
        ),
        migrations.RemoveField(
            model_name='servicelog',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='servicelog',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='servicelog',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicelog',
            name='statuscode',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Mechanic',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ServiceLog',
        ),
    ]
